language: ruby
os: linux
sudo: false

gemfile:
  - Gemfile
  - gemfiles/Gemfile.fluentd-0.14.10
  - gemfiles/Gemfile.td-agent-3.1.1
  - gemfiles/Gemfile.td-agent-3.2.0

env:
  - AWS_SDK_VERSION=DEFAULT
  - AWS_SDK_VERSION=1.3
  - AWS_SDK_VERSION=1.4

matrix:
  exclude:
    - gemfile: Gemfile
      env: AWS_SDK_VERSION=1.3
    - gemfile: Gemfile
      env: AWS_SDK_VERSION=1.4
  include:
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile.fluentd-0.14.10
    - rvm: 2.4.2 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.1.1/config/projects/td-agent3.rb#L17
      gemfile: gemfiles/Gemfile.td-agent-3.1.1
    - rvm: 2.4.4 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.2.0/config/projects/td-agent3.rb#L22
      gemfile: gemfiles/Gemfile.td-agent-3.2.0
  allow_failures:
    - env: AWS_SDK_VERSION=1.3
    - env: AWS_SDK_VERSION=1.4
  fast_finish: true

script: bundle exec rake test
