language: ruby

matrix:
  include:
    - rvm: 2.4.1
      os: linux
      gemfile: Gemfile
    - rvm: 2.1.10
      os: linux
      gemfile: gemfiles/Gemfile.td-agent-2.3.5

script: bundle exec rake test

sudo: false
